### ISSUE TITLE
STM32F103C8T6 Ethernet Client

### ISSUE THREAD

**Issue by elexal** [gilmaimon/ArduinoWebsockets#108]
hello
when i import an example then get error
In file included from C:\Users\MMAV\AppData\Local\Temp\arduino_modified_sketch_905279\STM32-Ethernet_AdvancedWebServer.ino:21:0:
C:\Users\MMAV\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32.h:36:3: error: #error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.
#error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.
^
In file included from C:\Users\MMAV\AppData\Local\Temp\arduino_modified_sketch_905279\STM32-Ethernet_AdvancedWebServer.ino:21:0:
C:\Users\MMAV\Documents\Arduino\libraries\EthernetWebServer_STM32\src/EthernetWebServer_STM32.h:74:22: fatal error: pgmspace.h: No such file or directory
#include <pgmspace.h>
^
compilation terminated.
Using library EthernetLarge-master at version 2.0.0 in folder: C:\Users\MMAV\Documents\Arduino\libraries\EthernetLarge-master
Using library WebSockets2_Generic-master at version 1.2.4 in folder: C:\Users\MMAV\Documents\Arduino\libraries\WebSockets2_Generic-master
Using library EthernetWebServer_STM32 at version 1.2.0 in folder: C:\Users\MMAV\Documents\Arduino\libraries\EthernetWebServer_STM32
Using library Functional-Vlpp at version 1.0.2 in folder: C:\Users\MMAV\Documents\Arduino\libraries\Functional-Vlpp
exit status 1
Error compiling for board Generic STM32F103C series.

**Comment by khoih-prog** [comment]
You're posting in the wrong library as you're using [WebSockets2_Generic](https://github.com/khoih-prog/WebSockets2_Generic).

But the real issue is you're using the wrong STM32 core : [**Roger Clark Arduino_STM32** core](https://github.com/rogerclarkmelbourne/Arduino_STM32) is not supported. Only [**Arduino Core for STM32** v2.0.0+](https://github.com/stm32duino/Arduino_Core_STM32) is.

Also select the STM32F103C with 64K+ memory (STM32F103C8, STM32F103CB, etc), then you'll be OK.

![Selection_797](https://user-images.githubusercontent.com/57012152/118306320-4683f500-b4b7-11eb-93d1-080f189214a6.png)
