### ISSUE TITLE
Possible to stream with ArduinoJSON?

### ISSUE THREAD

**Issue by AlexanderWingard** [gilmaimon/ArduinoWebsockets#53]
Hey!

This is a question. I'm using this lib together with https://arduinojson.org

My code currently looks like:
```c++
void onWsMsg(WebsocketsMessage message) {
  StaticJsonDocument<1024> doc;
  DeserializationError error = deserializeJson(doc, message.data());
  JsonObject obj = doc.as<JsonObject>();
```

and 
```c++
void sendJson(JsonObject obj) {
  char output[2048];
  serializeJson(obj, output);
  client.send(output);
}
```

My question is if it would be possible to hook ArduinoWebsockets up directly with the stream functionality of https://arduinojson.org/v6/api/json/deserializejson/ and https://arduinojson.org/v6/api/json/serializejson/ and if so how I would do that.

Cheers!

**Comment by gilmaimon** [comment]
Hi.

What kind of interface are you thinking about? You mean being able to do `client.send(jsonObj)`?

If you can add some code examples, it might help me understand exactly what you mean 😃 

Gil.

**Comment by AlexanderWingard** [comment]
No, I think I mean being able to do ```serializeJson(obj, client);``` and ```deserializeJson(doc, client);``` like he is able to do with the regular ```WiFiClient```

Why I started to look into this in the first place was that I caused a stack overflow by using that middle storage char[].

**Comment by gilmaimon** [comment]
You don't have to use a middle storage char[], you could use std::string which is returned by `msg.rawData()` which will not leak and is much safer.

I don't think it is correct to make `WebsocketsClient` a `Stream`, because a client is much more than just stream of data. For example, calling `serializeJson(obj, client)`, do you expect the message to be sent as binary message or text? Maybe as the context of a ping?

You could try and extend the library by making `WebsocketsClient` inherit from the Arduino Stream class, which will give you your desired behavior. Personally, I much prefer the explicit `sendJson` you implemented.

Gil.

**Comment by AlexanderWingard** [comment]
Ok, cool! I will use rawData.

Fair, I understand your points on not modifying this library. But maybe I will give it an attempt to do a subclass as you suggest or try as suggested in arduinojson implementing a ```CustomWriter``` and a ```CustomReader```. Not very skilled in C++ but I will share my results if I succeed.

Thanks!

**Comment by gilmaimon** [comment]
Best of luck! Let me know if you need help with it (my email is in my profile)
