### ISSUE TITLE
Please clarify behavior of message.send() on Arduino/ESP32 implementation

### ISSUE THREAD

**Issue by mbariola** [gilmaimon/ArduinoWebsockets#64]
@gilmaimon first of all, thanks for the really nice library. I am having a lot of fun playing with it on my esp32 boards!

There are a few things that maybe are obvious but I feel I don't grasp yet which maybe could benefit from a clarification. Namely, the behavior of send() under Arduino.
I am currently trying to put the esp32 to sleep, wake up, wait as little as possible after connection is (re)established, send a message to my ws server, then immediately go to sleep as soon as message is confirmed as either sent or failed to send. I have found no way to do so in the library as it is unclear to me whether client.send() is blocking, async and so on. 
I tried to discover it the hard way like this
```
    client.send((String)sendTime);
    // add optional delay here
    esp_deep_sleep_start();

```
and having my ws server log messages. I get messages only 50% of the time, which is strange, I should either get them 0% (or close to it, if async) or 100% of the time if blocking. If I add a 150ms delay, I get the messages every time  but it doesn't help keeping power consumption down as the esp32 is just twiddling thumbs for a preset amount of time without guarantee that actually the message got through. Of course I can address it in sw by sending the message back to esp32 and gong to sleep once I get it. Still, I feel I am missing something here. Could you clarify?

And yes I checked the wiki :-)

Thanks! and cheers

**Comment by gilmaimon** [comment]
Hi Massimiliano,

I should first say that I've never tested the library with deep sleep. `client.send` is indeed blocking, it will return only when sending the message failed/completed successfully. 

The networking in the library is relaying fully on the arduino libraries provided for esp8266 and esp32, if `send` does return `false`, meaning that it failed to send the message, it is probably not a logical issue with my library but rather an issue with the esp32 libraries.

The client itself that I'm using internally, has `setNoDelay(true)`, meaning that everything sent should be sent immediately (instead of waiting to goup small messages).  I suspect that internally, the esp32 libraries are async, and do not send the data immediately when calling `send`. You should try adding a `yield` call between the sleep and send, and if that does not work, try replacing the library client with a plain WiFiClient & set up a tcp server. See if the issue persist and if so, consider reporting it to the arduino-esp32 team.

Hopefully I understood everything correctly, let me know if a `yield` increases your success rate, or if a smaller delay time also worked.

Gil.

**Comment by mbariola** [comment]
I had a look at yield() but am not sure that will help or am not sure how to implement it. However, I did some brute tests:
client.send(...)
(delay)
esp_deep_sleep_start() requires a variable delay time that may be as low as 5 ms. As it was somewhat arbitrary, I preferred to change the check to a round trip one and sleeping when I get the packet back. It will be a longer amount of time but it will precisely be based on application behavior. 
Unfortunately I am under a deadline so I cannot try another TCP implementation but will try to do so as soon as convenient, then I'll update if I come up with something. Feel free to close the clarification request!

**Comment by gilmaimon** [comment]
Great. If you have any new info, I'll be glad to hear back from you.
I'll keep it open for few extra days, just in case you will have any news to share publicly.

Gil.
