### ISSUE TITLE
checking if client is connected

### ISSUE THREAD

**Issue by fdl333** [gilmaimon/ArduinoWebsockets#92]
**Describe the bug**
I've created a websocket client on esp32
cant find a way to check if client is connected before sending data in the loop(), and therefore reconnect ...

**To Reproduce**
Run sample, kill websocket server on host .. check if client is connected in loop, if not, reconnect

**Expected behavior**

**Code**

**Additional context**

**Comment by gilmaimon** [comment]
The `client` class has an `available` method which tells you exactly that. Now, sometimes when a server abruptly shuts-down, it might not notify all it's client that it is gone. That's why you can use `client.ping()`. If the server is connected, it will respond with a pong. If the server is gone, the esp32 will notice that no tcp ack is being sent back, so it will let you know that the server is gone (`client.available()` will return false).

Read more about it in the Wiki: https://github.com/gilmaimon/TinyWebsockets/wiki/Client#Managing-The-Connection

Gil.

**Comment by fdl333** [comment]
Thank you very much for clear and concise answer.

Francesco Facco de Lagarda
